### ISSUE TITLE
Generate annotated images of 3d structure

### ISSUE THREAD

**Issue by JudeWells** [vam-sin/domdet#33]

**Comment by alex-hh** [comment]
(If using python/jupyter)
ColabFold visualisation: https://github.com/sokrypton/ColabFold/blob/1e37ad16a384890d246524e89d9ae74ff894e461/colabfold/pdb.py
py3dmol Jupyter plugin docs: https://colab.research.google.com/drive/1T2zR59TXyWRcNxRgOAiqVPJWhep83NV_?usp=sharing
