### ISSUE TITLE
CASP test set: check why no chain / sequence for these entries

### ISSUE THREAD

**Issue by JudeWells** [vam-sin/domdet#42]
['T0851' 'T0953s1' 'T0953s2' 'T0957s1' 'T0957s2' 'T0968s1' 'T0968s2'
 'T0974s1' 'T0974s2' 'T0980s1' 'T0980s2' 'T0986s1' 'T0986s2' 'T1021s1'
 'T1021s2' 'T1021s3' 'T1022s1' 'T1022s2' 'T1036s1' 'T1045s1' 'T1045s2'
 'T1046s1' 'T1046s2' 'T1047s1' 'T1047s2' 'T1065s1' 'T1065s2']

These chains have a PDB-ID in the casp test set but do not have a sequence. Therefore has not been possible to determine which chain in the PDB file best matches them.
Note that all except one of these has the suffix eg 's1'

**Comment by alex-hh** [comment]
Looks like there are sequences for these on the target list pages https://predictioncenter.org/casp13/targetlist.cgi

**Comment by alex-hh** [comment]
Possibly they're duplicates? e.g. looks like there's a H0986 with two subunits, corresponding to T0986s1 and T0986s2.

Do you know what the difference between the H and T prefixes is?
