### ISSUE TITLE
Epoch test iterates over validation data muliple times instead of just once?

### ISSUE THREAD

**Issue by JudeWells** [vam-sin/domdet#50]
Epoch test gets called on each val_loader:
```
            for split_name, val_loader in zip(config["data"]["validation_splits"], val_loaders):
                test_metrics = epoch_test(
                    learner,
                    loader=val_loader,
                    evaluators=evaluators,
                    evaluator_names=evaluator_names,
                    prefix=split_name,
                    test_run=test_run,
                )
```
Then in each iteration inside epoch_test first it iterates over the val_loader calculating loss only.

Then it iterates over all of the evaluators:

```
    for evaluator_name, evaluator in zip(evaluator_names, evaluators):
        evaluator_metrics = evaluator(learner)
```

Often the evaluator has the exact same examples as the val_loader.
eg. evaluator names are:
`['domfilt_val', 'domfilt_val_multi', 'domfilt_val_many', 'casp_10_plus_test', 'casp_67_test']`

while the val_loaders are:
`['filt_val', 'filt_val_multi', 'filt_val_many']`

so I think at the end of every epoch it is running:
```

for loader in val_loaders:
    run(loader)
    for evaluator in evaluators:
        run(evaluator)
```

**Comment by alex-hh** [comment]
oh this was horrible nice fix!
